# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-10 02:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20170202_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 2, 10, 2, 10, 53, 326731, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
